### ISSUE TITLE
Piezo vs Buzzer

### ISSUE THREAD

**Issue by mildlyincompetent** [j5api/j5#101]
We have a piezo component, but SR used to have a buzzer component. Is there a particular reason we have decided to limit our component to piezoelectric buzzers rather than just having a generic "buzzer" component which can then be implemented in hardware via a piezo or via other mechanical / electromechanical means? I do not see any methods on the piezo that would not be possible for other types of buzzers - is there a plan to implement such methods?

**Comment by trickeydan** [comment]
Please see #40 Specifically https://github.com/j5api/j5/pull/40#discussion_r253651964
