### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by kierdavis** [j5api/j5#105]
As settled in #79, we should support 3.6. We're almost there, there's just a few things to polish up:

* [There's an instance where we assume `dict`s are sorted by insertion order.](https://github.com/j5api/j5/pull/74#discussion_r256566865). This is easily resolvable by using a `collections.OrderedDict`.
* The `Pipfile` specifies a minimum python version of 3.7, which needs to be changed.
* We should check the test suite works on 3.6. Even better if we can do this in CI (#104).
* Anything else??

**Comment by Skybound1** [comment]
This should be settled by #169
