### ISSUE TITLE
Logging Support

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#108]
We need support for logging. This should be done with the standard python `logging` library.

For now let's put it on `stdout`. Putting it in `journalctl` and on the usb drives can be worried about when we implement USB drives.

**Comment by trickeydan** [comment]
This could be useful for the test scripts, e.g just set the `LOGGING_LEVEL` to `DEBUG`

**Comment by trickeydan** [comment]
@sedders123 has made a start on this I believe.

**Comment by kierdavis** [comment]
I'm not sure what the scope of this issue is, but `sbot` already has some pretty good logging of software and firmware versions, and #369 will add logging of operations performed on components. I can't think of any other major things that should be logged.

**Comment by trickeydan** [comment]
This issue was technically completely, and I would argue is superseded by #370
