### ISSUE TITLE
Remove Demo Board and associated Backend.

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#115]
I initially created the demo board to help me build the structure of the project. After #93 is merged, we will have a full working example of a board, thus potentially making the `DemoBoard` redundant.

Is it worth removing this in favour of documentation of the `Board` definition and implementation process?

**Comment by kierdavis** [comment]
I agree that a real, well-defined `Board` serves as better documentation than a hypothetical `Board` with a blurry specification. Additionally, the fact that the power board is used in actual kits means its much harder for the code to become outdated without us knowing about it.

**Comment by trickeydan** [comment]
Blocked on #93
