### ISSUE TITLE
Document how to udev allow PowerBoard, etc

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#139]

**Comment by trickeydan** [comment]
After some fiddling, I have found that the following works for the power board:
```

**Comment by kierdavis** [comment]
It should be noted that the value of `GROUP` can be changed to any Unix group that it is convenient for the user to be a member of. I don't think I have a "plugdev" group on my system, but I do have "dialout" (which I am already a member of).

**Comment by trickeydan** [comment]
Motor Board:
```
# SR v4 Motor Board
SUBSYSTEM=="tty", DRIVERS=="ftdi_sio", ATTRS{interface}=="MCV4B", GROUP="plugdev", MODE="0666"
```
