### ISSUE TITLE
Should we have a j5BaseException?

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#142]
Should we have a base J5Exception that we use as our base Exception class, so that consumers can optionally just catch any of our stuff throwing?

**Comment by kierdavis** [comment]
I see a lot of other libraries do this, although personally I'd always want to catch the most specific exception I can. I don't have a preference on this.

**Comment by trickeydan** [comment]
I personally am in favour of this and I think @sedders123 is also.

**Comment by trickeydan** [comment]
Turns out that this is actually required for transitioning to `pyusb`.
