### ISSUE TITLE
Refactor extension registration

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#149]
We need to keep the auto-registration so that external modules can define `Board`s and have them register with the appropriate `Environment`.

@prophile is probably a good person to poke with this.

**Comment by trickeydan** [comment]
The solution to this issue should also fix the issue where the backend has to be imported, but not directly used, resulting in messy code and a linting error

**Comment by trickeydan** [comment]
I'm delaying this to v0.0.4

**Comment by trickeydan** [comment]
This still needs doing, but there are other things that are blocking shipping for Smallpiece. We can deal with slightly messy code for a bit.

**Comment by trickeydan** [comment]
I think what the fundamental issue here is to do with auto-registration of classes. That's what the issue is.

I've done some research into plugin frameworks and none of them do exactly what we want. 

I think that explicit registration of modules is the correct approach to take.

**Comment by kierdavis** [comment]
> I think that explicit registration of modules is the correct approach to take.

Agreed. It's also less magical and thus more Pythonic.
