### ISSUE TITLE
Use poetry run in docs/Makefile

### ISSUE THREAD

**Issue by kierdavis** [j5api/j5#188]
It would be nice to be able to make running `make docs-html` from the top-level directory do the equivalent of `cd docs; poetry run make html`.

**Comment by trickeydan** [comment]
I'd recommend using `make -C docs`, so that we can run `make docs html`, or `make docs pdf` etc

**Comment by kierdavis** [comment]
That works; in that case we should still update `docs/Makefile` to use `poetry run` (otherwise `sphinxbuild` is not found on my system).
