### ISSUE TITLE
Fix 'Using type() instead of isinstance() for a typecheck.' issue in tests\backends\hardware\test_env.py

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#196]
[CodeFactor](https://www.codefactor.io/repository/github/j5api/j5) found an issue: Using type() instead of isinstance() for a typecheck.

It's currently on:
[tests\backends\hardware\test_env.py:9
](https://www.codefactor.io/repository/github/j5api/j5/source/master/tests/backends/hardware/test_env.py#L9)Commit 85a5ddb8c6693fbf43b85891bf36ced1de3320f9

**Comment by Shivam60** [comment]
Greetings, Thanks for marking it good first issue. I would like to contribute to resolving this issue.

**Comment by trickeydan** [comment]
Hi @Shivam60,
Thanks for your help! We welcome all people to our projects, no matter their experience or ability.

I can see that you've already forked the repository. If you make your changes in their and then create a pull request against this repository `master`, we can then review the code, run automated tests, approve and merge.
