### ISSUE TITLE
Type[Backend] should be used instead of Backend

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#198]
While we're at it, I think `backend` is supposed to be a `Type[Backend]` here, because we later call `backend.discover()` (or will do after #195 is merged). Also, there isn't a board in this context that `backend` would correspond to if it was an instance rather than a subclass.

_Originally posted by @kierdavis in https://github.com/j5api/j5/pull/193_

**Comment by kierdavis** [comment]
[This was fixed](https://github.com/j5api/j5/pull/195/files#diff-17dc87c8b02117dbd0910ebd418b5483R75) by #195.
