### ISSUE TITLE
BoardGroup.singular uses Exception

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#249]
File "/home/dan/.cache/pypoetry/virtualenvs/sbot-py3.7/lib/python3.7/site-packages/j5/boards/board.py", line 94, in singular
    raise Exception("There is more than one or zero boards connected.")

This should be a more specific error.

**Comment by kierdavis** [comment]
I don't think any of the standard python Exceptions describe this scenario very well, so I think it's sensible to define our own exception type for this. I don't have a good name for it though.

**Comment by kierdavis** [comment]
Somewhat related: I find this error message quite grammatically unclear. Perhaps something like

> Expected exactly one board to be connected

would be clearer? Or even:

> Expected exactly one `{type(board).__name__}` board to be connected

**Comment by trickeydan** [comment]
Given that we have the `board.name` attribute, I agree.

**Comment by trickeydan** [comment]
This was fixed in #336
