### ISSUE TITLE
Stricter Board Typing is possible

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#283]
See https://mypy.readthedocs.io/en/latest/kinds_of_types.html#the-type-of-class-objects

**Comment by kierdavis** [comment]
As far as I can tell we already use the feature you've linked in our codebase in various places. Could you elaborate on what improvements you think we can make?

**Comment by trickeydan** [comment]
Specifically, using bound typevariables. e.g `TypeVar("T", bound='Board')

**Comment by trickeydan** [comment]
Looks like this has been done already!
