### ISSUE TITLE
Bound Type Variable on Backend.discover

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#305]
It is possible to use a bound type variable on ~`Board.discover`~ `Backend.discover` to more tightly type the return type.

**Comment by kierdavis** [comment]
`Board.discover` hasn't existed since 229fdcf9bfcdc27dfab404a6d1e9af14835fb429. Do you mean `Backend.discover`?

**Comment by trickeydan** [comment]
> `Board.discover` hasn't existed since [229fdcf](https://github.com/j5api/j5/commit/229fdcf9bfcdc27dfab404a6d1e9af14835fb429). Do you mean `Backend.discover`?

Erm, yeah I did

**Comment by trickeydan** [comment]
I have attempted this and it would require to use bound Type Variables in *a lot* of places. Enough that the increase in knowledge to use the project outweighs the benefits that we get imo.

I personally would like to mark this as a `wontfix` for this reason.

**Comment by trickeydan** [comment]
@kierdavis ?

**Comment by trickeydan** [comment]
If it is agreed that this is `wontfix`, we should close this issue.

**Comment by kierdavis** [comment]
Yeah, this sounds like a "version 2.0" task, if anything.
