### ISSUE TITLE
Review whether BoardGroups should be ordered or not

### ISSUE THREAD

**Issue by kierdavis** [j5api/j5#37]
There is no inherent order to the boards attached to a robot. We should make a decision whether we want to keep this notion (requiring users to address boards by serial number), or to assign an order (in which case we need to be explicit about what that order is e.g. sort by serial number)

This is relevant to #23.

I'm happy to implement the outcome of this decision in a PR.

**Comment by trickeydan** [comment]
I definitely agree that something should be done here. A set should be used if they are inherently unordered, but I would definitely like to keep the ability to iterate through boards.
I suggest discussing this evening.

**Comment by kierdavis** [comment]
It's worth noting that sets can still be iterated over (but the order of iteration should be considered nondeterministic). Let's discuss further this evening as you suggest.

**Comment by kierdavis** [comment]
I'm waiting for #25 to be reviewed and merged before starting work on this.
