### ISSUE TITLE
BoardGroup.__iter__ should return a disposable object, not itself

### ISSUE THREAD

**Issue by kierdavis** [j5api/j5#38]
Currently, `BoardGroup.__iter__` returns `self`, and uses an attribute of `self` to maintain state. This confuses the lifetime of a collection with the lifetime of an iteration over that collection. This method should really return a distinct object encapsulating the statefulness of iteration (`self.boards.values()`, for example).

If this gets a :+1: or two I'll go ahead and make a PR.

**Comment by trickeydan** [comment]
Yeah I agree. The python docs for iteration are not the best.

**Comment by kierdavis** [comment]
I'm waiting for #25 to be reviewed and merged before starting work on this.
