### ISSUE TITLE
Refactor to remove technical debt in Raw USB Comms

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#395]
```
        if usb_error.errno == 110:  # "operation timed out" 

            message += "; are you sure the servo board is being correctly powered?" 

        elif usb_error.errno == 32:  # pipe error 

            message += "; are you sending buzz commands to the power board too quickly?" 
```

We should have a general mechanism to give suggested problems.

Board specific stuff should not be in the RawUSB backend.

**Comment by kierdavis** [comment]
Currently it's not easy to add board-specific functionality to this decorator.

To be honest, I'm not a big fan of this decorator anyway. It breaks type checking and I think handling errors explicitly at each point where they can be raised allows more detail to be kept (e.g. explanatory messages like these) is better than having effectively one giant catch-all.
