### ISSUE TITLE
Separate Zoloto into it's own package

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#402]
Ok, I have a suggestion. 

As a trial for #97 we could move zoloto to it's own package. This will require a reasonable amount of work, but we need to put it in anyway.

As a temporary solution, I'm ok removing this as a dev package. It's broken on some systems evidently.

_Originally posted by @trickeydan in https://github.com/j5api/j5/issues/363#issuecomment-526943265_

**Comment by kierdavis** [comment]
I suggest we start by pulling out all the vision stuff together (which is the minimum needed for #363), and then work on decoupling the zoloto-specific stuff from the non-zoloto-specific stuff.

**Comment by trickeydan** [comment]
I'm currently working on a PR to enable plugin functionality, I'll submit that soon and then we can begin the package separation.

I think it would be good to use a monorepo for this. @mildlyincompetent is likely to be better at explaining the advantages than me.

**Comment by sedders123** [comment]
I'm +1 on this idea, also have no objections to monorepo.
