### ISSUE TITLE
Explore auto-releasing

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#403]
- Annotated, Signed Git Tags.

I'll have a look at this at some point, but I want to concentrate on some other things for now, and we do currently have a working release process.

**Comment by trickeydan** [comment]
I'm unassigning myself as I think there are more important things to do.

**Comment by trickeydan** [comment]
GitHub actions is a much nicer way to do this.

**Comment by sedders123** [comment]
I have implemented a [GitHub Action](https://github.com/sedders123/phial/blob/develop/.github/workflows/cd.yml) to deploy to PyPi for one of my personal projects. While it probably can't be copied exactly it may serve as a decent jumping off point.

**Comment by trickeydan** [comment]
> I have implemented a [GitHub Action](https://github.com/sedders123/phial/blob/develop/.github/workflows/cd.yml) to deploy to PyPI for one of my personal projects. While it probably can't be copied exactly it may serve as a decent jumping off point.

I really like the `verify` stage of this.
