### ISSUE TITLE
Example code in README can easily fall out of date

### ISSUE THREAD

**Issue by kierdavis** [j5api/j5#419]
I think this has happened more than once. It would we great if we could typecheck it, though I'm not  sure we can do that without pulling it out into a separate file.

**Comment by trickeydan** [comment]
I have investigated this, and mypy doesn't support this OOTB.

I have a dodgy idea that involves regexing out the code using sed and then putting it in a separate `readme.py` during the tests. We could add it to the `Makefile` and the `readme*.py` to the `.gitignore`.
