### ISSUE TITLE
Motor power tests don't seem to work as intended

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#431]
Quite surprised that this wasn't caught in tests. I should rely on them less when accepting changes.

This should be tested [here](https://github.com/j5api/j5/blob/4e847333a2a93b1c710dad060f2b56553e58a1da/tests/components/test_motor.py#L86) but doesn't appear to for some reason.

_Originally posted by @trickeydan in https://github.com/j5api/j5/pull/428/review_comment/create_

**Comment by kierdavis** [comment]
If you set `motor.power` to `1` (*not* `1.0`), I don't think the [bounds check](https://github.com/j5api/j5/blob/4e847333a2a93b1c710dad060f2b56553e58a1da/j5/components/motor.py#L64) actually gets run, because `isinstance(1, float) == False`.
