### ISSUE TITLE
__repr__

### ISSUE THREAD

**Issue by Skybound1** [j5api/j5#48]
The return value of `__repr__` should look like a valid Python expression that could be passed into `eval()` to create an object with the same value (or as close as)

https://docs.python.org/3/library/functions.html#repr

**Comment by trickeydan** [comment]
Upon some implementation, I'm uncertain that implementing `__repr__`  for everything is actually useful. The default python one is useful enough, and we cannot test it properly either as it always boils down to an object at a memory address eventually.

**Comment by kierdavis** [comment]
Makes sense. We have `__str__` for most if not all things anyway. I'm happy for this to be closed as a wontfix.
