### ISSUE TITLE
Support SR v4 Power Board

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#59]
Support SR v4 Power Board.

Prerequisites:
- ~~Button Support~~ - #44 
- ~~Power Output Support~~ - #61
- ~~Battery (voltage / status)~~ - #62
- ~~Piezo~~ - #60

**Comment by kierdavis** [comment]
Since I happen to be looking at this, the mapping of output numbers (0 to 5) used in the wire protocol to outputs labelled on the board is as follows:

```
0 - H0
1 - H1
2 - L0
3 - L1
4 - L2
5 - L3
```

For consistency we should use the same numbering for identifying `PowerOutput` components.
