### ISSUE TITLE
Support SR Ruggeduino

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#65]
Requires GPIO Pin -  #43 

We need to think about how to support direct communication. Perhaps some sort of serial component?

**Comment by kierdavis** [comment]
By direct communication, I assume you mean exposing a channel for competitors' robot code to talk to their custom ruggeduino firmware?

**Comment by trickeydan** [comment]
> By direct communication, I assume you mean exposing a channel for competitors' robot code to talk to their custom ruggeduino firmware?

Exactly that.

**Comment by trickeydan** [comment]
I think this probably needs breaking up a bit.

- [ ] Generalisation of Arduino-style boards
- [ ] Generalisation of ArduinoBackend
- [ ] Work out how to send custom commands to the Ruggeduino (I think a new Component is in order here)
- [ ] Implementation of RuggeduinoBoard and Backends.

There are three states that a Ruggeduino can be in:

- Standard SR firmware.
- Extended SR firmware (i.e enable command component)
- Completely custom firmware
	- `sr-robot` has an ignore option for this. We should probably add one of these too.
	- Expose a list of ignored serial devices so that students can use them.
