### ISSUE TITLE
Support SourceBots Arduino

### ISSUE THREAD

**Issue by trickeydan** [j5api/j5#66]
Requires:
- Servos - #42 
- GPIO - #43 
- Ultrasound - This may or may not want to be a component. Consider this when we get here.

**Comment by kierdavis** [comment]
I think canonically ultrasound sensors *should* be a component; however this may require a rethink of the component API due to how ultrasound sensors are addressed as a pair of pin numbers (trigger pin and echo pin).

**Comment by trickeydan** [comment]
For ultrasound sensors, we could have a 'virtual' `Component`. Two `GPIOPin`s can be passed to it in the constructor?

**Comment by kierdavis** [comment]
yeah. There's no reason why we couldn't have high-level components built on top of low-level components. I'm thinking something like:

```python
class ServoAssembly:
  ...
  def ultrasound_sensor(self, trigger_pin, echo_pin):
    if isinstance(trigger_pin, int): trigger_pin = self.gpio[trigger_pin]
    if isinstance(echo_pin, int): echo_pin = self.gpio[echo_pin]
    return UltrasoundProximitySensor(self._backend, trigger_pin, echo_pin)
  ...
class UltrasoundProximitySensor:
  @property
  def distance(self):
    return self._backend.read_ultrasound_sensor(self._trigger_pin.identifier, self._echo_pin.identifier)
```

**Comment by kierdavis** [comment]
Ultrasound isn't implemented in the hardware backend yet. Fortunately this is just a matter of extending the existing `SBArduinoHardwareBackend` with `UltrasoundInterface`; pretty much all of the infrastructure is already in place.

**Comment by kierdavis** [comment]
#365 fixed this.
