### ISSUE TITLE
[FEATURE] BoardGroup __repr__

### ISSUE THREAD

**Issue by kierdavis** [j5api/j5#73]
`Board` has `__repr__`, so it makes sense for `BoardGroup` to have one too.

**Comment by trickeydan** [comment]
#48 is relevant here.

**Comment by Shivam60** [comment]
Hey, I would like to take up this issue if no one has been assigned to it.

**Comment by Shivam60** [comment]
Are we expecting the following output for the __repr__ ?

BoardGroup(MotorBoard,ServoBoard,Ruggeduin)

**Comment by trickeydan** [comment]
The constructor for a `BoardGroup` is:
```python
def __init__(self, board: Type[Board], backend: Backend):
    self.board_class = board
    self._backend: Backend = backend
    self.boards: Dict[str, Board] = OrderedDict()

    self.update_boards()
```
See [here](https://github.com/j5api/j5/blob/3990b4e79add2a5797ccbd089d8ec1311d1aa813/j5/boards/board.py#L81)

#48 gives some info on what a `__repr__` should look like. Probably something like `BoardGroup(PowerBoard, SRv4PowerBoardHardwareBackend`

**Comment by trickeydan** [comment]
@Shivam60 How've you been getting on with this? Need any help?

**Comment by trickeydan** [comment]
Removing from milestone due to inactive contributor.

@Shivam60 Would you still like to do this?

**Comment by Shivam60** [comment]
hey so sorry for my inactivity. I just checked my email's as I was preoccupied with my university exams. I am on it

**Comment by Shivam60** [comment]
Guys I am sorry. My laptop's screen broke and I have to travel to different city to get a replacement. It looks like it LL take a week. I am sorry. I request you to remove me from this issue since I won't be able to code till I get a replacement. I am sorry :(

**Comment by trickeydan** [comment]
> Guys I am sorry. My laptop's screen broke and I have to travel to different city to get a replacement. It looks like it LL take a week. I am sorry. I request you to remove me from this issue since I won't be able to code till I get a replacement. I am sorry :(

That's alright. Hope everything works out for you and your laptop. Thanks for your help so far :)
