### ISSUE TITLE
Ensure arduino pins are set as outputs when changing mode

### ISSUE THREAD

**Issue by RealOrangeOne** [j5api/j5#758]
Currently, when setting a pin as `OUTPUT`, the arduino never gets the message. For all other pins it works as expected.

The cause of this is in:

https://github.com/j5api/j5/blob/4517772684615516e73a09edad751df6ed17bb44/j5/backends/hardware/sr/v4/ruggeduino.py#L103-L107

Note how only the state is set, not the pin mode, which causes weird things to happen. This could be patched with firmware, but that's a lot of work, and arguably fixing it here is the correct course of action anyway.

**Comment by WillB97** [comment]
There are kind of 2 issues here:
1. `_update_digital_pin` doesn't set the output mode
2. Setting the pin mode and setting the output state should be separate functions as we don't want to repeatedly set the output mode

**Comment by trickeydan** [comment]
Issue confirmed.
