### ISSUE TITLE
Edit on GitHub Button on ReadTheDocs 404s

### ISSUE THREAD

**Issue by mildlyincompetent** [j5api/j5#81]
It is not very good.

**Comment by trickeydan** [comment]
For more detail on this issue, there seems to be an unwanted `origin` appearing in the URLs.

Docs to fix this issue are: https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html?highlight=github#confval-github_url

**Comment by Skybound1** [comment]
Changed readthedocs to use the master branch over latest. This fixed the issue
